n1 = int(input('Um valor'))
n2 = int(input('Outro valor'))
s= (n1+n2)
m = (n1*n2)
d = (n1/n2)
di = (n1//n2)
p= (n1**n2)
print('A soma é {}\n A multiplicação é {}\n A divisão é {}\n A divisão inteira é {:.3f}\n e a potenciação é {}\n'.format(s,m,d,di,p))
